udate some tools version

diff --git a/su-tools/check-su b/su-tools/check-su
--- a/su-tools/check-su
+++ b/su-tools/check-su
@@ -28,16 +28,15 @@ PHONE_CHECK_SU=$PHONE_TMP_DIR/phone-check-su
 function getRet()
 {
 	adb wait-for-device
-	adb push $CHECK_SU $PHONE_CHECK_SU > /dev/null 2>&1
+	adb push $CHECK_SU $PHONE_CHECK_SU  2>&1
 	adb shell chmod 777 $PHONE_CHECK_SU
-
-	ret=$(adb shell sh $PHONE_CHECK_SU 2>&1 | grep OK)
-	if [ "x$ret" != "x" ]; then
+	adb shell su -c cp /system/build.prop /sdcard 2>&1
+	if [ $? != "0" ];then
+		echo "Error: su is wrong"
+		return 1
+	else
 		echo "su is ok"
 		return 0
-	else
-		#echo "Error: su is wrong"
-		return 1
 	fi
 }
 
